import 'package:rechoice_app/models/model/category_model.dart';
import 'package:rechoice_app/models/model/items_model.dart';
import 'package:rechoice_app/models/model/users_model.dart';

class DummyData {
  //Category dummy data

  static List<ItemCategoryModel> getCategories() {
    return [
      ItemCategoryModel(categoryID: 0, name: 'Electronics'),
      ItemCategoryModel(categoryID: 1, name: 'Fashion'),
      ItemCategoryModel(categoryID: 2, name: 'Personal care'),
      ItemCategoryModel(categoryID: 3, name: 'Book/Study'),
      ItemCategoryModel(categoryID: 4, name: 'Home/Living'),
    ];
  }

  static List<Items> getFeaturedProducts() {
    final categories = getCategories();
    return [
      // Electronics (categoryID: 0)
      Items(
        itemID: 6,
        title: 'CLASSIC WHITE TEE',
        category: categories[0],
        brand: 'Uniqlo',
        condition: 'Brand New',
        price: 120,
        quantity: 1,
        description:
            '100% cotton crew neck t-shirt. Essential wardrobe staple with comfortable fit and breathable fabric. Perfect for everyday wear.',
        status: 'Available',
        imagePath: 'assets/images/electronics/electronics_1.png',
      ),
      Items(
        itemID: 7,
        title: 'POLO SHIRT',
        category: categories[0],
        brand: 'Ralph Lauren',
        condition: 'Like New',
        price: 450,
        quantity: 1,
        description:
            'Classic polo shirt with signature embroidered pony. Made from soft cotton mesh with ribbed collar and cuffs.',
        status: 'Available',
        imagePath: 'assets/images/electronics/electronics_2.png',
      ),
      Items(
        itemID: 8,
        title: 'OVERSIZED HOODIE',
        category: categories[0],
        brand: 'H&M',
        condition: 'Brand New',
        price: 280,
        quantity: 1,
        description:
            'Relaxed fit hoodie in cotton blend. Features drawstring hood, kangaroo pocket, and ribbed trim. Street style comfort.',
        status: 'Available',
        imagePath: 'assets/images/electronics/electronics_3.png',
      ),
      Items(
        itemID: 9,
        title: 'DENIM JACKET',
        category: categories[0],
        brand: "Levi's",
        condition: 'Good',
        price: 550,
        quantity: 1,
        description:
            'Classic trucker jacket in premium denim. Features button closure, chest pockets, and adjustable side tabs. Timeless layering piece.',
        status: 'Available',
        imagePath: 'assets/images/electronics/electronics_4.png',
      ),
      Items(
        itemID: 10,
        title: 'STRIPED BUTTON-UP',
        category: categories[0],
        brand: 'Zara',
        condition: 'Brand New',
        price: 320,
        quantity: 1,
        description:
            'Slim fit shirt with vertical stripes. Made from breathable cotton with button-down collar. Perfect for smart casual looks.',
        status: 'Available',
        imagePath: 'assets/images/electronics/electronics_5.png',
      ),
      // Fashion (categoryID: 1)
      Items(
        itemID: 11,
        title: 'LEATHER SNEAKERS',
        category: categories[1],
        brand: 'Adidas',
        condition: 'Like New',
        price: 380,
        quantity: 1,
        description: 'Low-cut leather sneakers with rubber sole. Clean and minimal design.',
        status: 'Available',
        imagePath: 'assets/images/fashion/fashion_1.png',
      ),
      Items(
        itemID: 12,
        title: 'SLIM FIT JEANS',
        category: categories[1],
        brand: "Levi's",
        condition: 'Good',
        price: 420,
        quantity: 1,
        description: 'Mid-rise slim jeans made from durable denim.',
        status: 'Available',
        imagePath: 'assets/images/fashion/fashion_2.png',
      ),
      Items(
        itemID: 13,
        title: 'ANALOG WATCH',
        category: categories[1],
        brand: 'Casio',
        condition: 'Brand New',
        price: 260,
        quantity: 1,
        description: 'Stainless steel case with leather strap and quartz movement.',
        status: 'Available',
        imagePath: 'assets/images/fashion/fashion_3.png',
      ),
      Items(
        itemID: 14,
        title: 'CANVAS BACKPACK',
        category: categories[1],
        brand: 'Herschel',
        condition: 'Good',
        price: 300,
        quantity: 1,
        description: 'Durable backpack with padded shoulder straps.',
        status: 'Available',
        imagePath: 'assets/images/fashion/fashion_4.png',
      ),
      Items(
        itemID: 15,
        title: 'BASEBALL CAP',
        category: categories[1],
        brand: 'New Era',
        condition: 'Like New',
        price: 120,
        quantity: 1,
        description: 'Adjustable cotton cap with embroidered logo.',
        status: 'Available',
        imagePath: 'assets/images/fashion/fashion_5.png',
      ),

      // Personal Care (categoryID: 2)
      Items(
        itemID: 16,
        title: 'ELECTRIC SHAVER',
        category: categories[2],
        brand: 'Philips',
        condition: 'Good',
        price: 350,
        quantity: 1,
        description: 'Rechargeable shaver with triple-head system.',
        status: 'Available',
        imagePath: 'assets/images/personalCare/personal_1.png',
      ),
      Items(
        itemID: 17,
        title: 'HAIR DRYER',
        category: categories[2],
        brand: 'Panasonic',
        condition: 'Like New',
        price: 280,
        quantity: 1,
        description: 'Compact hair dryer with heat protection.',
        status: 'Available',
        imagePath: 'assets/images/personalCare/personal_2.png',
      ),
      Items(
        itemID: 18,
        title: 'SKINCARE SET',
        category: categories[2],
        brand: 'The Ordinary',
        condition: 'Brand New',
        price: 200,
        quantity: 1,
        description: 'Basic skincare routine set for daily use.',
        status: 'Available',
        imagePath: 'assets/images/personalCare/personal_3.png',
      ),
      Items(
        itemID: 19,
        title: 'DIGITAL WEIGHING SCALE',
        category: categories[2],
        brand: 'Xiaomi',
        condition: 'Good',
        price: 150,
        quantity: 1,
        description: 'Glass surface scale with digital display.',
        status: 'Available',
        imagePath: 'assets/images/personalCare/personal_4.png',
      ),
      Items(
        itemID: 20,
        title: 'MANICURE KIT',
        category: categories[2],
        brand: 'Generic',
        condition: 'Brand New',
        price: 90,
        quantity: 1,
        description: 'Stainless steel grooming tools set.',
        status: 'Available',
        imagePath: 'assets/images/personalCare/personal_5.png',
      ),

      // Book/Study (categoryID: 3)
      Items(
        itemID: 21,
        title: 'DATA STRUCTURES BOOK',
        category: categories[3],
        brand: 'Pearson',
        condition: 'Good',
        price: 180,
        quantity: 1,
        description: 'Reference book for computer science students.',
        status: 'Available',
        imagePath: 'assets/images/books/books_1.png',
      ),
      Items(
        itemID: 22,
        title: 'SCIENTIFIC CALCULATOR',
        category: categories[3],
        brand: 'Casio',
        condition: 'Like New',
        price: 130,
        quantity: 1,
        description: 'Non-programmable calculator for exams.',
        status: 'Available',
        imagePath: 'assets/images/books/books_2.png',
      ),
      Items(
        itemID: 23,
        title: 'STUDY DESK LAMP',
        category: categories[3],
        brand: 'IKEA',
        condition: 'Good',
        price: 110,
        quantity: 1,
        description: 'LED desk lamp with adjustable arm.',
        status: 'Available',
        imagePath: 'assets/images/books/books_3.png',
      ),
      Items(
        itemID: 24,
        title: 'NOTEBOOK SET',
        category: categories[3],
        brand: 'Muji',
        condition: 'Brand New',
        price: 80,
        quantity: 1,
        description: 'Plain paper notebooks for daily notes.',
        status: 'Available',
        imagePath: 'assets/images/books/books_4.png',
      ),
      Items(
        itemID: 25,
        title: 'LAPTOP STAND',
        category: categories[3],
        brand: 'Baseus',
        condition: 'Like New',
        price: 140,
        quantity: 1,
        description: 'Aluminium stand for ergonomic viewing.',
        status: 'Available',
        imagePath: 'assets/images/books/books_5.png',
      ),

      // Home/Living (categoryID: 4)
      Items(
        itemID: 26,
        title: 'CERAMIC MUG SET',
        category: categories[4],
        brand: 'IKEA',
        condition: 'Brand New',
        price: 100,
        quantity: 1,
        description: 'Set of four ceramic mugs.',
        status: 'Available',
        imagePath: 'assets/images/home-living/home_1.png',
      ),
      Items(
        itemID: 27,
        title: 'THROW PILLOW',
        category: categories[4],
        brand: 'H&M Home',
        condition: 'Like New',
        price: 90,
        quantity: 1,
        description: 'Cotton cushion cover with soft filling.',
        status: 'Available',
        imagePath: 'assets/images/home-living/home_2.png',
      ),
      Items(
        itemID: 28,
        title: 'TABLE CLOCK',
        category: categories[4],
        brand: 'Seiko',
        condition: 'Good',
        price: 160,
        quantity: 1,
        description: 'Quartz table clock with silent movement.',
        status: 'Available',
        imagePath: 'assets/images/home-living/home_3.png',
      ),
      Items(
        itemID: 29,
        title: 'STORAGE BOX',
        category: categories[4],
        brand: 'IKEA',
        condition: 'Brand New',
        price: 70,
        quantity: 1,
        description: 'Plastic storage box with lid.',
        status: 'Available',
        imagePath: 'assets/images/home-living/home_4.png',
      ),
      Items(
        itemID: 30,
        title: 'BED SHEET SET',
        category: categories[4],
        brand: 'Akemi',
        condition: 'Like New',
        price: 250,
        quantity: 1,
        description: 'Queen size cotton bed sheet set.',
        status: 'Available',
        imagePath: 'assets/images/home-living/home_5.png',
      ),

    ];
  }

  static List<Users> getCurrentUser() {
    return [
      Users(
        userID: 1,
        name: 'John Doe',
        email: 'test123@gmail.com',
        password: 'test123',
        profilePic: 'assets/images/google.png',
        bio: 'bio',
        reputationScore: 10.00,
      ),
    ];
  }
}
