import 'package:rechoice_app/models/model/category_model.dart';
import 'package:rechoice_app/models/model/items_model.dart';
import 'package:rechoice_app/models/model/users_model.dart';

class DummyData {
  static final DummyData _instance = DummyData._internal();
  factory DummyData() => _instance;
  DummyData._internal();

  // Current logged in user (for demo purposes)
  static int currentUserID = 1;
  //Category dummy data

  static List<ItemCategoryModel> getCategories() {
    return [
      ItemCategoryModel(
        categoryID: 0,
        name: 'Electronics',
        iconName: 'electronics_icon',
      ),
      ItemCategoryModel(
        categoryID: 1,
        name: 'Fashion',
        iconName: 'fashion_icon',
      ),
      ItemCategoryModel(
        categoryID: 2,
        name: 'Personal care',
        iconName: 'personal_care_icon',
      ),
      ItemCategoryModel(
        categoryID: 3,
        name: 'Book/Study',
        iconName: 'book_study_icon',
      ),
      ItemCategoryModel(
        categoryID: 4,
        name: 'Home/Living',
        iconName: 'home_living_icon',
      ),
    ];
  }

  static List<Items> getFeaturedProducts() {
    final categories = getCategories();
    return [
      // Electronics (categoryID: 0)
      Items(
        itemID: 6,
        title: 'IPHONE 13 PRO',
        category: categories[0],
        brand: 'Apple',
        condition: 'Like New',
        price: 3500,
        quantity: 1,
        description:
            'A-grade iPhone 13 Pro with 256GB storage. No scratches, fully functional.',
        status: 'Available',
        imagePath: 'assets/images/electronics/electronics_1.png',
        postedDate: DateTime.now(),
        sellerID: 2,
      ),
      Items(
        itemID: 7,
        title: 'GALAXY TAB S8',
        category: categories[0],
        brand: 'Samsung',
        condition: 'Good',
        price: 2800,
        quantity: 1,
        description:
            '11-inch Android tablet with S Pen. Minor signs of use but otherwise in perfect working condition.',
        status: 'Available',
        imagePath: 'assets/images/electronics/electronics_2.png',
        postedDate: DateTime.now(),
        sellerID: 3,
      ),
      Items(
        itemID: 8,
        title: 'DELL XPS 15 LAPTOP',
        category: categories[0],
        brand: 'Dell',
        condition: 'Brand New',
        price: 6500,
        quantity: 1,
        description:
            'Unused Dell XPS 15 with Intel Core i7, 16GB RAM, and 512GB SSD. Still in original packaging.',
        status: 'Available',
        imagePath: 'assets/images/electronics/electronics_3.png',
        postedDate: DateTime.now(),
        sellerID: 4,
      ),
      Items(
        itemID: 9,
        title: 'SONY WH-1000XM4 HEADPHONES',
        category: categories[0],
        brand: "Sony",
        condition: 'Good',
        price: 950,
        quantity: 1,
        description:
            'Industry-leading noise-canceling headphones. Great sound quality, comes with original case.',
        status: 'Available',
        imagePath: 'assets/images/electronics/electronics_4.png',
        postedDate: DateTime.now(),
        sellerID: 2,
      ),
      Items(
        itemID: 10,
        title: 'LOGITECH MX MASTRE 3 MOUSE',
        category: categories[0],
        brand: 'Logitech',
        condition: 'Like New',
        price: 350,
        quantity: 1,
        description:
            'Ergonomic wireless mouse for professionals. Used for a short period, looks and works like new.',
        status: 'Available',
        imagePath: 'assets/images/electronics/electronics_5.png',
        postedDate: DateTime.now(),
        sellerID: 3,
      ),
      // Fashion (categoryID: 1)
      Items(
        itemID: 11,
        title: 'LEATHER SNEAKERS',
        category: categories[1],
        brand: 'Adidas',
        condition: 'Like New',
        price: 380,
        quantity: 1,
        description:
            'Low-cut leather sneakers with rubber sole. Clean and minimal design.',
        status: 'Available',
        imagePath: 'assets/images/fashion/fashion_1.png',
        postedDate: DateTime.now(),
        sellerID: 1,
      ),
      Items(
        itemID: 12,
        title: 'SLIM FIT JEANS',
        category: categories[1],
        brand: "Levi's",
        condition: 'Good',
        price: 420,
        quantity: 1,
        description: 'Mid-rise slim jeans made from durable denim.',
        status: 'Available',
        imagePath: 'assets/images/fashion/fashion_2.png',
        postedDate: DateTime.now(),
        sellerID: 1,
      ),
      Items(
        itemID: 13,
        title: 'ANALOG WATCH',
        category: categories[1],
        brand: 'Casio',
        condition: 'Brand New',
        price: 260,
        quantity: 1,
        description:
            'Stainless steel case with leather strap and quartz movement.',
        status: 'Available',
        imagePath: 'assets/images/fashion/fashion_3.png',
        postedDate: DateTime.now(),
        sellerID: 1,
      ),
      Items(
        itemID: 14,
        title: 'CANVAS BACKPACK',
        category: categories[1],
        brand: 'Herschel',
        condition: 'Good',
        price: 300,
        quantity: 1,
        description: 'Durable backpack with padded shoulder straps.',
        status: 'Available',
        imagePath: 'assets/images/fashion/fashion_4.png',
        postedDate: DateTime.now(),
        sellerID: 1,
      ),
      Items(
        itemID: 15,
        title: 'BASEBALL CAP',
        category: categories[1],
        brand: 'New Era',
        condition: 'Like New',
        price: 120,
        quantity: 1,
        description: 'Adjustable cotton cap with embroidered logo.',
        status: 'Available',
        imagePath: 'assets/images/fashion/fashion_5.png',
        postedDate: DateTime.now(),
        sellerID: 1,
      ),

      // Personal Care (categoryID: 2)
      Items(
        itemID: 16,
        title: 'ELECTRIC SHAVER',
        category: categories[2],
        brand: 'Philips',
        condition: 'Good',
        price: 350,
        quantity: 1,
        description: 'Rechargeable shaver with triple-head system.',
        status: 'Available',
        imagePath: 'assets/images/personalCare/personal_1.png',
        postedDate: DateTime.now(),
        sellerID: 1,
      ),
      Items(
        itemID: 17,
        title: 'HAIR DRYER',
        category: categories[2],
        brand: 'Panasonic',
        condition: 'Like New',
        price: 280,
        quantity: 1,
        description: 'Compact hair dryer with heat protection.',
        status: 'Available',
        imagePath: 'assets/images/personalCare/personal_2.png',
        postedDate: DateTime.now(),
        sellerID: 1,
      ),
      Items(
        itemID: 18,
        title: 'SKINCARE SET',
        category: categories[2],
        brand: 'The Ordinary',
        condition: 'Brand New',
        price: 200,
        quantity: 1,
        description: 'Basic skincare routine set for daily use.',
        status: 'Available',
        imagePath: 'assets/images/personalCare/personal_3.png',
        postedDate: DateTime.now(),
        sellerID: 1,
      ),
      Items(
        itemID: 19,
        title: 'DIGITAL WEIGHING SCALE',
        category: categories[2],
        brand: 'Xiaomi',
        condition: 'Good',
        price: 150,
        quantity: 1,
        description: 'Glass surface scale with digital display.',
        status: 'Available',
        imagePath: 'assets/images/personalCare/personal_4.png',
        postedDate: DateTime.now(),
        sellerID: 1,
      ),
      Items(
        itemID: 20,
        title: 'MANICURE KIT',
        category: categories[2],
        brand: 'Generic',
        condition: 'Brand New',
        price: 90,
        quantity: 1,
        description: 'Stainless steel grooming tools set.',
        status: 'Available',
        imagePath: 'assets/images/personalCare/personal_5.png',
        postedDate: DateTime.now(),
        sellerID: 1,
      ),

      // Book/Study (categoryID: 3)
      Items(
        itemID: 21,
        title: 'DATA STRUCTURES BOOK',
        category: categories[3],
        brand: 'Pearson',
        condition: 'Good',
        price: 180,
        quantity: 1,
        description: 'Reference book for computer science students.',
        status: 'Available',
        imagePath: 'assets/images/books/books_1.png',
        postedDate: DateTime.now(),
        sellerID: 1,
      ),
      Items(
        itemID: 22,
        title: 'SCIENTIFIC CALCULATOR',
        category: categories[3],
        brand: 'Casio',
        condition: 'Like New',
        price: 130,
        quantity: 1,
        description: 'Non-programmable calculator for exams.',
        status: 'Available',
        imagePath: 'assets/images/books/books_2.png',
        postedDate: DateTime.now(),
        sellerID: 1,
      ),
      Items(
        itemID: 23,
        title: 'STUDY DESK LAMP',
        category: categories[3],
        brand: 'IKEA',
        condition: 'Good',
        price: 110,
        quantity: 1,
        description: 'LED desk lamp with adjustable arm.',
        status: 'Available',
        imagePath: 'assets/images/books/books_3.png',
        postedDate: DateTime.now(),
        sellerID: 1,
      ),
      Items(
        itemID: 24,
        title: 'NOTEBOOK SET',
        category: categories[3],
        brand: 'Muji',
        condition: 'Brand New',
        price: 80,
        quantity: 1,
        description: 'Plain paper notebooks for daily notes.',
        status: 'Available',
        imagePath: 'assets/images/books/books_4.png',
        postedDate: DateTime.now(),
        sellerID: 1,
      ),
      Items(
        itemID: 25,
        title: 'LAPTOP STAND',
        category: categories[3],
        brand: 'Baseus',
        condition: 'Like New',
        price: 140,
        quantity: 1,


        description: 'Aluminium stand for ergonomic viewing.',
        status: 'Available',
        imagePath: 'assets/images/books/books_5.png',
        postedDate: DateTime.now(),
        sellerID: 1,
      ),

      // Home/Living (categoryID: 4)
      Items(
        itemID: 26,
        title: 'CERAMIC MUG SET',
        category: categories[4],
        brand: 'IKEA',
        condition: 'Brand New',
        price: 100,
        quantity: 1,
        description: 'Set of four ceramic mugs.',
        status: 'Available',
        imagePath: 'assets/images/home-living/home_1.png',
        postedDate: DateTime.now(),
        sellerID: 1,
      ),
      Items(
        itemID: 27,
        title: 'THROW PILLOW',
        category: categories[4],
        brand: 'H&M Home',
        condition: 'Like New',
        price: 90,
        quantity: 1,
        description: 'Cotton cushion cover with soft filling.',
        status: 'Available',
        imagePath: 'assets/images/home-living/home_2.png',
        postedDate: DateTime.now(),
        sellerID: 1,
      ),
      Items(
        itemID: 28,
        title: 'TABLE CLOCK',
        category: categories[4],
        brand: 'Seiko',
        condition: 'Good',
        price: 160,
        quantity: 1,
        description: 'Quartz table clock with silent movement.',
        status: 'Available',
        imagePath: 'assets/images/home-living/home_3.png',
        postedDate: DateTime.now(),
        sellerID: 1,
      ),
      Items(
        itemID: 29,
        title: 'STORAGE BOX',
        category: categories[4],
        brand: 'IKEA',
        condition: 'Brand New',
        price: 70,
        quantity: 1,
        description: 'Plastic storage box with lid.',
        status: 'Available',
        imagePath: 'assets/images/home-living/home_4.png',
        postedDate: DateTime.now(),
        sellerID: 1,
      ),
      Items(
        itemID: 30,
        title: 'BED SHEET SET',
        category: categories[4],
        brand: 'Akemi',
        condition: 'Like New',
        price: 250,
        quantity: 1,
        description: 'Queen size cotton bed sheet set.',
        status: 'Available',
        imagePath: 'assets/images/home-living/home_5.png',
        postedDate: DateTime.now(),
        sellerID: 1,
      ),
    ];
  }

  // ==================== USERS ====================
  static final List<Users> _users = [
    Users(
      uid: '',
      userID: 1,
      name: 'John Doe',
      email: 'john.doe@email.com',
      profilePic: 'https://ui-avatars.com/api/?name=John+Doe',
      bio:
          'Student at Allamanda College passionate about technology and learning. Always looking for new opportunities to grow and connect with like-minded individuals.',
      reputationScore: 4.5,
      status: UserStatus.active,
      joinDate: DateTime(2024, 1, 15),
      lastLogin: DateTime.now().subtract(const Duration(hours: 2)),
      role: UserRole.buyer,
      totalListings: 2,
      totalPurchases: 5,
      totalSales: 3,
      phoneNumber: '+60 12-345 6789',
      address:
          'Allamanda College, Universiti Malaysia Sarawak 94300, Kota Samarahan, Sarawak',
    ),
    Users(
      uid: '',

      userID: 2,
      name: 'Sarah M.',
      email: 'sarah@student.unimas.my',
      
      profilePic: 'https://ui-avatars.com/api/?name=Sarah+M',
      bio:
          'Tech enthusiast and gadget lover. Selling preloved electronics in great condition.',
      reputationScore: 4.8,
      status: UserStatus.active,
      joinDate: DateTime(2024, 2, 20),
      lastLogin: DateTime.now().subtract(const Duration(days: 1)),
      role: UserRole.seller,
      totalListings: 15,
      totalPurchases: 8,
      totalSales: 12,
      phoneNumber: '+60 11-234 5678',
      address: 'UNIMAS Student Housing',
    ),
    Users(
             uid: '',

      userID: 3,
      name: 'Ahmad R.',
      email: 'ahmad@student.unimas.my',
      
      profilePic: 'https://ui-avatars.com/api/?name=Ahmad+R',
      bio: 'Engineering student. Selling items I no longer need.',
      reputationScore: 4.2,
      status: UserStatus.active,
      joinDate: DateTime(2023, 11, 10),
      lastLogin: DateTime.now().subtract(const Duration(hours: 5)),
      role: UserRole.seller,
      totalListings: 8,
      totalPurchases: 12,
      totalSales: 6,
      phoneNumber: '+60 13-456 7890',
      address: 'Kolej Kediaman',
    ),
    Users(
             uid: '',

      userID: 4,
      name: 'Syafiq',
      email: 'syaqchen@student.unimas.my',
      profilePic: 'https://ui-avatars.com/api/?name=Syafiq',
      bio: 'Trusted seller with verified items. Fast response!',
      reputationScore: 4.9,
      status: UserStatus.active,
      joinDate: DateTime(2026, 3, 1),
      lastLogin: DateTime.now().subtract(const Duration(minutes: 30)),
      role: UserRole.seller,
      totalListings: 25,
      totalPurchases: 3,
      totalSales: 20,
      phoneNumber: '+60 12-345 6789',
      address: 'Kota Samarahan',
    ),
    Users(
             uid: '',

      userID: 5,
      name: 'Emma Wilson',
      email: 'emma@student.unimas.my',
      profilePic: 'https://ui-avatars.com/api/?name=Emma+Wilson',
      bio: 'Final year student clearing out my stuff before graduation.',
      reputationScore: 3.8,
      status: UserStatus.suspended,
      joinDate: DateTime(2024, 2, 28),
      lastLogin: DateTime.now().subtract(const Duration(days: 7)),
      role: UserRole.seller,
      totalListings: 5,
      totalPurchases: 10,
      totalSales: 4,
      phoneNumber: '+60 14-567 8901',
      address: 'Student Accommodation',
    ),
    // Admin users
    Users(
             uid: '',

      userID: 100,
      name: 'Admin',
      email: 'admin@rechoice.com',
      profilePic: 'https://ui-avatars.com/api/?name=Admin',
      bio: 'Platform administrator',
      reputationScore: 5.0,
      status: UserStatus.active,
      joinDate: DateTime(2023, 1, 1),
      lastLogin: DateTime.now(),
      role: UserRole.admin,
      totalListings: 0,
      totalPurchases: 0,
      totalSales: 0,
    ),
  ];
}
